import type { HeroSlideData, ProductWithRelations } from '@/types'

export const mockHeroSlides: HeroSlideData[] = [
  {
    id: '1',
    title: 'Professional in\nConstruction material',
    subtitle: 'Multi-Seller Consolidation|Combine multiple suppliers, optimize logistics, save time and cost.|Light Steel Structure Engineering sourcing|High-quality steel structure materials, one-stop sourcing for your projects.',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1920&h=600&q=75&fit=crop',
    ctaText: 'Shanghai cargo Plus',
    ctaLink: '/products',
    position: 0,
    isActive: true,
  },
]

export const mockProducts: ProductWithRelations[] = [
  {
    id: '1',
    name: 'Heavy-Duty Steel Rebar Bundle',
    slug: 'heavy-duty-steel-rebar-bundle',
    description: 'High-tensile steel rebar for concrete reinforcement. Grade 60, 20mm diameter.',
    price: 299.99,
    compareAtPrice: 349.99,
    stockQuantity: 500,
    categoryId: 'cat-1',
    sellerId: 'seller-1',
    status: 'active',
    specifications: { grade: '60', diameter: '20mm', length: '12m', weight: '30kg/bundle' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-1',
        productId: '1',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&q=75&fit=crop',
        altText: 'Steel rebar bundle',
        position: 0,
      },
    ],
    category: { id: 'cat-1', name: 'Steel & Metal', slug: 'steel-metal', description: null, imageUrl: null },
    seller: { id: 'seller-1', businessName: 'SteelPro China', businessEmail: 'info@steelpro.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '2',
    name: 'Industrial Welding Robot Arm',
    slug: 'industrial-welding-robot-arm',
    description: '6-axis welding robot arm with precision control. Ideal for automotive and manufacturing.',
    price: 12999.99,
    compareAtPrice: null,
    stockQuantity: 15,
    categoryId: 'cat-2',
    sellerId: 'seller-2',
    status: 'active',
    specifications: { axes: '6', payload: '10kg', reach: '1.4m', repeatability: '±0.05mm' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-2',
        productId: '2',
        url: 'https://images.unsplash.com/photo-1563207153-f403bf289096?w=400&h=400&q=75&fit=crop',
        altText: 'Industrial robot arm',
        position: 0,
      },
    ],
    category: { id: 'cat-2', name: 'Robots', slug: 'robots', description: null, imageUrl: null },
    seller: { id: 'seller-2', businessName: 'RoboTech Shanghai', businessEmail: 'sales@robotech.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '3',
    name: 'Portland Cement (50 bags)',
    slug: 'portland-cement-50-bags',
    description: 'Type I/II Portland cement. 40kg bags, 50-bag pallet. CSA A3000 certified.',
    price: 449.99,
    compareAtPrice: 499.99,
    stockQuantity: 200,
    categoryId: 'cat-3',
    sellerId: 'seller-1',
    status: 'active',
    specifications: { type: 'Type I/II', weight: '40kg/bag', quantity: '50 bags', certification: 'CSA A3000' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-3',
        productId: '3',
        url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&h=400&q=75&fit=crop',
        altText: 'Portland cement bags',
        position: 0,
      },
    ],
    category: { id: 'cat-3', name: 'Cement & Concrete', slug: 'cement-concrete', description: null, imageUrl: null },
    seller: { id: 'seller-1', businessName: 'SteelPro China', businessEmail: 'info@steelpro.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '4',
    name: 'Autonomous Floor Cleaning Robot',
    slug: 'autonomous-floor-cleaning-robot',
    description: 'Commercial-grade autonomous floor scrubber for warehouses and factories.',
    price: 5499.99,
    compareAtPrice: 6200.00,
    stockQuantity: 30,
    categoryId: 'cat-2',
    sellerId: 'seller-2',
    status: 'active',
    specifications: { coverage: '2000m²/hr', battery: '8hr', width: '85cm', connectivity: 'WiFi + 4G' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-4',
        productId: '4',
        url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&q=75&fit=crop',
        altText: 'Autonomous cleaning robot',
        position: 0,
      },
    ],
    category: { id: 'cat-2', name: 'Robots', slug: 'robots', description: null, imageUrl: null },
    seller: { id: 'seller-2', businessName: 'RoboTech Shanghai', businessEmail: 'sales@robotech.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '5',
    name: 'Ceramic Floor Tiles (Box of 10)',
    slug: 'ceramic-floor-tiles-box-10',
    description: 'Premium ceramic floor tiles. 60x60cm, anti-slip finish. Suitable for indoor/outdoor.',
    price: 89.99,
    compareAtPrice: null,
    stockQuantity: 1000,
    categoryId: 'cat-4',
    sellerId: 'seller-3',
    status: 'active',
    specifications: { size: '60x60cm', finish: 'Anti-slip', material: 'Ceramic', coverage: '3.6m²/box' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-5',
        productId: '5',
        url: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=400&h=400&q=75&fit=crop',
        altText: 'Ceramic floor tiles',
        position: 0,
      },
    ],
    category: { id: 'cat-4', name: 'Tiles & Flooring', slug: 'tiles-flooring', description: null, imageUrl: null },
    seller: { id: 'seller-3', businessName: 'TileWorld Guangzhou', businessEmail: 'export@tileworld.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '6',
    name: 'Drone Inspection Robot',
    slug: 'drone-inspection-robot',
    description: 'Industrial inspection drone with thermal camera. For building and infrastructure inspection.',
    price: 3299.99,
    compareAtPrice: null,
    stockQuantity: 20,
    categoryId: 'cat-2',
    sellerId: 'seller-2',
    status: 'active',
    specifications: { flightTime: '45min', camera: '4K + Thermal', range: '7km', windResistance: 'Level 7' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-6',
        productId: '6',
        url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=400&q=75&fit=crop',
        altText: 'Industrial inspection drone',
        position: 0,
      },
    ],
    category: { id: 'cat-2', name: 'Robots', slug: 'robots', description: null, imageUrl: null },
    seller: { id: 'seller-2', businessName: 'RoboTech Shanghai', businessEmail: 'sales@robotech.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '7',
    name: 'Structural Steel I-Beam (6m)',
    slug: 'structural-steel-i-beam-6m',
    description: 'Hot-rolled structural steel I-beam. W200x100 profile, 6 metre length.',
    price: 189.99,
    compareAtPrice: 219.99,
    stockQuantity: 300,
    categoryId: 'cat-1',
    sellerId: 'seller-1',
    status: 'active',
    specifications: { profile: 'W200x100', length: '6m', weight: '22kg/m', grade: 'A36' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-7',
        productId: '7',
        url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&q=75&fit=crop',
        altText: 'Structural steel I-beam',
        position: 0,
      },
    ],
    category: { id: 'cat-1', name: 'Steel & Metal', slug: 'steel-metal', description: null, imageUrl: null },
    seller: { id: 'seller-1', businessName: 'SteelPro China', businessEmail: 'info@steelpro.cn', logoUrl: null, status: 'active' },
  },
  {
    id: '8',
    name: 'Collaborative Robot (Cobot) UR5',
    slug: 'collaborative-robot-cobot-ur5',
    description: 'Universal collaborative robot for assembly, pick & place, and quality inspection tasks.',
    price: 28999.99,
    compareAtPrice: null,
    stockQuantity: 8,
    categoryId: 'cat-2',
    sellerId: 'seller-2',
    status: 'active',
    specifications: { payload: '5kg', reach: '850mm', axes: '6', safetyRating: 'ISO 10218' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: 'img-8',
        productId: '8',
        url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=400&q=75&fit=crop',
        altText: 'Collaborative robot cobot',
        position: 0,
      },
    ],
    category: { id: 'cat-2', name: 'Robots', slug: 'robots', description: null, imageUrl: null },
    seller: { id: 'seller-2', businessName: 'RoboTech Shanghai', businessEmail: 'sales@robotech.cn', logoUrl: null, status: 'active' },
  },
]
